# Generated by Django 3.0.6 on 2024-05-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('line', models.IntegerField(choices=[(1, '函数主线'), (2, '几何与代数主线'), (3, '概率与统计主线'), (4, '数学建模主线')])),
                ('desc', models.TextField()),
                ('file', models.FileField(upload_to='math_culture/share/')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
