# Generated by Django 3.0.6 on 2024-05-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='line',
            field=models.CharField(choices=[('函数主线', '函数主线'), ('几何与代数主线', '几何与代数主线'), ('概率与统计主线', '概率与统计主线'), ('数学建模主线', '数学建模主线')], max_length=7),
        ),
    ]
