# Generated by Django 3.0.6 on 2024-05-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_culture', '0002_auto_20240522_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
