# Generated by Django 3.0.6 on 2022-08-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_and_grade', models.CharField(max_length=10)),
                ('dormitory', models.CharField(max_length=5)),
                ('decrease', models.CharField(max_length=5)),
                ('reason', models.CharField(max_length=20)),
            ],
        ),
    ]
