# Generated by Django 3.0.6 on 2022-09-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_record_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='class_and_grade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='reason',
            field=models.CharField(max_length=50),
        ),
    ]
