# Generated by Django 3.0.6 on 2022-09-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20220902_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='decrease',
            field=models.IntegerField(choices=[('说话', 1), ('卫生', 1), ('迟到', 1), ('旷寝', 5), ('外出', 1), ('未出操', 1), ('未关灯', 1)]),
        ),
    ]
