# Generated by Django 3.0.6 on 2022-09-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_auto_20220908_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='decrease',
            field=models.IntegerField(choices=[(1, '说话'), (1, '卫生'), (1, '迟到'), (5, '旷寝'), (1, '外出'), (1, '未出操'), (1, '未关灯')]),
        ),
    ]
