# Generated by Django 3.0.6 on 2022-09-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_record_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='tp',
            field=models.CharField(choices=[('卫生', '卫生'), ('说话', '说话'), ('迟到', '迟到'), ('旷寝', '旷寝'), ('外出', '外出'), ('未出操', '未出操'), ('未关灯', '未关灯')], default='卫生', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='decrease',
            field=models.IntegerField(default=1),
        ),
    ]
