# Generated by Django 3.0.6 on 2022-09-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_auto_20220913_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='tm',
            field=models.CharField(choices=[('午休纪律', '午休纪律'), ('下午卫生', '下午卫生'), ('晚休纪律', '晚休纪律'), ('早上卫生', '早上卫生')], default='午休纪律', max_length=10),
        ),
    ]
