# Generated by Django 3.0.6 on 2022-09-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_record_tm'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='grade',
            field=models.CharField(default='', max_length=5),
        ),
    ]
