# Generated by Django 3.0.6 on 2022-09-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0012_record_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='grade',
            field=models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三')], default='高一', max_length=5),
        ),
    ]
