# Generated by Django 3.0.6 on 2022-09-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0013_auto_20220914_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='grade',
            field=models.IntegerField(choices=[(1, '高一'), (2, '高二'), (3, '高三')], default=1),
        ),
    ]
