# Generated by Django 3.0.6 on 2022-09-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0014_auto_20220914_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='tm',
            field=models.CharField(choices=[('1午休纪律', '午休纪律'), ('2下午卫生', '下午卫生'), ('3晚休纪律', '晚休纪律'), ('4早上卫生', '早上卫生')], default='午休纪律', max_length=10),
        ),
    ]
