# Generated by Django 3.0.6 on 2022-09-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0016_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(choices=[('boy', 'boy'), ('girl', 'girl')], default='boy', max_length=5),
        ),
    ]
