# Generated by Django 3.0.6 on 2022-09-22 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0017_record_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2022, 9, 22, 9, 11, 38, 269357, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='record',
            name='date_group_str',
            field=models.CharField(default='', max_length=20),
        ),
    ]
