# Generated by Django 3.0.6 on 2024-06-25 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0018_auto_20220922_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(choices=[('2023~2024学年', '2023~2024学年'), ('2022~2023学年', '2022~2023学年')], max_length=11)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 10, 9, 44, 309782, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='record',
            name='tm',
            field=models.CharField(choices=[('1午休纪律', '午休纪律'), ('2下午内务', '下午内务'), ('3晚休纪律', '晚休纪律'), ('4早上内务', '早上内务')], default='午休纪律', max_length=10),
        ),
    ]
