# Generated by Django 3.0.6 on 2024-06-25 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0019_auto_20240625_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 11, 7, 44, 983301, tzinfo=utc)),
        ),
    ]
