# Generated by Django 3.0.6 on 2024-06-27 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0021_auto_20240627_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='t1',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t10',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t11',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t12',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t2',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t3',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t4',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t5',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t6',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t7',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t8',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t9',
            field=models.IntegerField(choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '极不满意')], default=5),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2024, 6, 27, 3, 16, 57, 440311, tzinfo=utc)),
        ),
    ]
