# Generated by Django 3.0.6 on 2024-06-27 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0022_auto_20240627_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='t13',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='t14',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2024, 6, 27, 6, 53, 38, 620665, tzinfo=utc)),
        ),
    ]
