# Generated by Django 3.0.6 on 2024-10-03 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0024_auto_20240813_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('未知', '未知')], default='未知', max_length=2),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='school_year',
            field=models.CharField(choices=[('2024~2025学年', '2024~2025学年'), ('2023~2024学年', '2023~2024学年')], max_length=11),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='id_number',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2024, 10, 3, 2, 33, 51, 614510, tzinfo=utc)),
        ),
    ]
