# Generated by Django 3.0.6 on 2024-10-07 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0025_auto_20241003_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='bed',
            field=models.IntegerField(choices=[(0, '公共区域'), (1, '1号床'), (2, '2号床'), (3, '3号床'), (4, '4号床'), (5, '5号床'), (6, '6号床'), (7, '7号床'), (8, '8号床')], default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='student',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 13, 38, 2, 976833, tzinfo=utc)),
        ),
    ]
