# Generated by Django 3.0.6 on 2024-10-09 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0026_auto_20241007_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='bed_area',
            field=models.CharField(default='公共区域', max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2024, 10, 9, 13, 36, 6, 593832, tzinfo=utc)),
        ),
    ]
