# Generated by Django 3.0.6 on 2025-06-12 03:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0027_auto_20241009_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2025, 6, 12, 3, 6, 30, 113015, tzinfo=utc)),
        ),
    ]
