# Generated by Django 3.0.6 on 2025-11-24 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0028_auto_20250612_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='school_year',
            field=models.CharField(choices=[('2025~2026学年', '2025~2026学年'), ('2024~2025学年', '2024~2025学年')], max_length=11),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2025, 11, 24, 8, 48, 0, 659051, tzinfo=utc)),
        ),
    ]
