# Generated by Django 3.0.6 on 2026-04-02 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0029_auto_20251124_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='no_dorm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2026, 4, 2, 8, 56, 12, 137999, tzinfo=utc)),
        ),
    ]
