# Generated by Django 3.0.6 on 2026-04-09 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0030_auto_20260402_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2026, 4, 9, 12, 0, 50, 40099, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='GoHomeStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2026, 4, 9))),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('school_time', models.CharField(max_length=200)),
                ('school_time_show', models.CharField(max_length=200)),
                ('school_time_n', models.IntegerField()),
                ('date_show', models.CharField(max_length=20)),
                ('tm', models.IntegerField(choices=[(0, '未开始'), (1, '走读中'), (2, '已结束')])),
                ('active', models.BooleanField()),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('student_relative', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scores.NewStudent')),
            ],
        ),
    ]
