# Generated by Django 3.0.6 on 2026-04-13 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0031_auto_20260409_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='gohomestudent',
            name='tm_show',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='gohomestudent',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 4, 13)),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2026, 4, 13, 13, 33, 25, 996307, tzinfo=utc)),
        ),
    ]
