# Generated by Django 3.0.6 on 2026-09-10 01:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0033_auto_20260604_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gohomestudent',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 9, 10)),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='school_year',
            field=models.CharField(choices=[('2026~2027学年', '2026~2027学年'), ('2025~2026学年', '2025~2026学年')], max_length=11),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2026, 9, 10, 1, 12, 25, 400709, tzinfo=utc)),
        ),
    ]
