# Generated by Django 3.0.6 on 2026-09-10 01:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0034_auto_20260910_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_group',
            field=models.DateField(default=datetime.datetime(2026, 9, 10, 1, 17, 20, 262657, tzinfo=utc)),
        ),
    ]
