# Generated by Django 3.0.6 on 2023-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1)),
                ('card_type', models.CharField(default='身份证', max_length=5)),
                ('id_number', models.CharField(max_length=18)),
                ('gender1', models.CharField(max_length=1)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
