# Generated by Django 3.0.6 on 2025-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('2024-2025_1', '2024~2025学年第1学期'), ('2024-2025_2', '2024~2025学年第2学期'), ('2025-2026_1', '2025~2026学年第1学期'), ('2025-2026_2', '2025~2026学年第2学期'), ('2026-2027_1', '2026~2027学年第1学期')], max_length=11)),
                ('title', models.CharField(max_length=23)),
                ('active', models.BooleanField(default=True)),
                ('items_max', models.TextField()),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
