# Generated by Django 3.0.6 on 2025-07-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班'), ('高三1班', '高三1班'), ('高三2班', '高三2班'), ('高三3班', '高三3班'), ('高三4班', '高三4班'), ('高三5班', '高三5班'), ('高三6班', '高三6班'), ('高三7班', '高三7班'), ('高三8班', '高三8班'), ('高三9班', '高三9班'), ('高三10班', '高三10班'), ('高三11班', '高三11班'), ('高三12班', '高三12班')], max_length=5)),
                ('grade_num', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('cs', models.CharField(max_length=2)),
                ('cs_int', models.IntegerField()),
                ('xlsx_file', models.FileField(upload_to='praises/class_submit/')),
                ('total', models.IntegerField()),
                ('student_list', models.TextField()),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('task_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='praises.Task')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('praise_name', models.CharField(max_length=10)),
                ('cert', models.ImageField(upload_to='praises/cert/')),
                ('cert_simple', models.ImageField(upload_to='praises/cert_simple/')),
                ('class_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='praises.ClassSubmit')),
            ],
        ),
    ]
