# Generated by Django 3.0.6 on 2025-07-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0003_task_cert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmit',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
