# Generated by Django 3.0.6 on 2023-11-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('year', models.CharField(max_length=4)),
                ('active', models.BooleanField(default=True)),
                ('added', models.IntegerField(default=0)),
                ('max_len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('card_type', models.IntegerField(choices=[(1, '居民二代身份证')])),
                ('id_number', models.CharField(max_length=18)),
                ('phone_number', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1)),
                ('middle_school', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='zzbm/')),
                ('room', models.CharField(default='未分配', max_length=3)),
                ('seat', models.CharField(default='未分配', max_length=3)),
                ('exam_id', models.CharField(default='未分配', max_length=12)),
                ('pwd', models.CharField(default='000000', max_length=6)),
                ('num', models.IntegerField()),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('task_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zzbm.Task')),
            ],
        ),
    ]
