# Generated by Django 3.0.6 on 2023-11-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
