# Generated by Django 3.0.6 on 2023-12-21 09:07

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0002_task_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='zzbm/', verbose_name='一寸照片'),
        ),
    ]
