# Generated by Django 3.0.6 on 2024-02-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0003_auto_20231221_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(choices=[('素描或创意画', '素描或创意画'), ('书法或国画', '书法或国画')], default='素描或创意画', max_length=6),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
