# Generated by Django 3.0.6 on 2024-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0004_auto_20240227_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.CharField(default='', max_length=19),
        ),
    ]
