# Generated by Django 3.0.6 on 2024-02-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0005_auto_20240227_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='format_start_time',
            field=models.CharField(default='', max_length=16),
        ),
    ]
