# Generated by Django 3.0.6 on 2024-02-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0006_task_format_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='open_download',
            field=models.BooleanField(default=False),
        ),
    ]
