# Generated by Django 3.0.6 on 2024-02-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0007_task_open_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_room',
            field=models.IntegerField(default=0),
        ),
    ]
