# Generated by Django 3.0.6 on 2024-03-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0008_task_max_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(choices=[('素描或创意画', '素描或创意画'), ('书法或国画', '书法或国画')], max_length=6),
        ),
    ]
