# Generated by Django 3.0.6 on 2024-03-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0009_auto_20240301_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.CharField(choices=[('A', 'A(+50)'), ('B', 'B(+40)'), ('C', 'C(+30)'), ('D', 'D(不合格)'), ('O', 'O(未设置)')], default='O', max_length=1),
        ),
    ]
