# Generated by Django 3.0.6 on 2024-04-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0010_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mr1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='mr2',
            field=models.IntegerField(default=0),
        ),
    ]
