# Generated by Django 3.0.6 on 2024-04-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0011_auto_20240416_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='turn1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='turn2',
            field=models.IntegerField(default=0),
        ),
    ]
