# Generated by Django 3.0.6 on 2024-04-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0012_auto_20240416_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_give',
            field=models.BooleanField(default=False),
        ),
    ]
