# Generated by Django 3.0.6 on 2024-04-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0013_task_auto_give'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=25),
        ),
    ]
