# Generated by Django 3.0.6 on 2024-04-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0014_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='add_method',
            field=models.IntegerField(choices=[(1, '自行报名'), (2, '模板导入')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_len',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='mr2',
            field=models.IntegerField(default=36),
        ),
    ]
