# Generated by Django 3.0.6 on 2024-04-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0015_auto_20240424_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='task',
            name='mr2',
            field=models.IntegerField(default=50),
        ),
    ]
