# Generated by Django 3.0.6 on 2024-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0016_auto_20240429_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='miss',
            field=models.BooleanField(default=False),
        ),
    ]
