# Generated by Django 3.0.6 on 2024-05-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0017_student_miss'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='can_que',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.CharField(choices=[('A', 'A(合格)'), ('B', 'B(合格)'), ('C', 'C(合格)'), ('D', 'D(不合格)'), ('O', 'O(未设置)')], default='O', max_length=1),
        ),
    ]
