# Generated by Django 3.0.6 on 2025-04-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0018_auto_20240522_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='format_start_time_1',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_1',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.CharField(choices=[('A', 'A(优秀)'), ('B', 'B(良好)'), ('C', 'C(合格)'), ('D', 'D(不合格)'), ('O', 'O(未设置)')], default='O', max_length=1),
        ),
    ]
