# Generated by Django 3.0.6 on 2025-05-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0019_auto_20250430_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_turn',
            field=models.IntegerField(default=0),
        ),
    ]
