# Generated by Django 3.0.6 on 2025-05-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0020_task_start_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.CharField(choices=[('A', '合格'), ('D', '不合格'), ('O', '未设置')], default='O', max_length=1),
        ),
    ]
