# Generated by Django 3.0.6 on 2025-05-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0021_auto_20250517_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='format_start_time_2',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='format_start_time_3',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_2',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_3',
            field=models.CharField(default='', max_length=19),
        ),
    ]
