# Generated by Django 3.0.6 on 2025-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0022_auto_20250526_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='format_start_time_4',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='format_start_time_5',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_4',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_5',
            field=models.CharField(default='', max_length=19),
        ),
    ]
