# Generated by Django 3.0.6 on 2025-05-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0023_auto_20250527_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='format_start_time',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='format_start_time_1',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='format_start_time_2',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='format_start_time_3',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='format_start_time_4',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='format_start_time_5',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time_1',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time_2',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time_3',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time_4',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time_5',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
    ]
