# Generated by Django 3.0.6 on 2026-05-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0026_auto_20260506_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='full_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='full_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='full_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='full_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='full_5',
            field=models.BooleanField(default=False),
        ),
    ]
