# Generated by Django 3.0.6 on 2026-05-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0027_auto_20260506_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='full',
            new_name='full1',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='full_1',
            new_name='full1_1',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='full_2',
            new_name='full1_2',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='full_3',
            new_name='full1_3',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='full_4',
            new_name='full1_4',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='full_5',
            new_name='full1_5',
        ),
        migrations.AddField(
            model_name='task',
            name='full2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='full2_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='full2_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='full2_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='full2_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='full2_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_ob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_ob_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_ob_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_ob_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_ob_4',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_ob_5',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
