# Generated by Django 3.0.6 on 2026-05-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0028_auto_20260506_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exam_time_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='exam_time_active_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='exam_time_active_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='exam_time_active_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='exam_time_active_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='exam_time_active_5',
            field=models.BooleanField(default=True),
        ),
    ]
