# Generated by Django 3.0.6 on 2026-05-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0030_auto_20260506_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mr1_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='mr2_5',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='task',
            name='mr_show',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='mr_show_1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='mr_show_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='mr_show_3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='mr_show_4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='mr_show_5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='total1_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='total2_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='total_show',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='total_show_1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='total_show_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='total_show_3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='total_show_4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='total_show_5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='num8',
            field=models.CharField(choices=[('0', '2026年5月20日 下午15:00 —— 17:00'), ('1', '2026年5月22日 上午8:30 —— 10:30'), ('2', '2026年5月25日 上午10:00 —— 12:00')], default='0', max_length=1),
        ),
    ]
