# Generated by Django 3.0.6 on 2026-05-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0031_auto_20260507_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_school_desc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
