# Generated by Django 3.0.6 on 2026-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0032_student_middle_school_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_school',
            field=models.CharField(max_length=30),
        ),
    ]
