# Generated by Django 3.0.6 on 2026-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzbm', '0034_auto_20260522_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='white_name',
            field=models.BooleanField(default=False),
        ),
    ]
