# Generated by Django 3.0.6 on 2023-04-20 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('2023-04', '2023年4月'), ('2023-03', '2023年3月'), ('2023-02', '2023年2月'), ('2023-01', '2023年1月'), ('2022-12', '2022年12月'), ('2022-11', '2022年11月')], max_length=8)),
                ('week1', models.IntegerField(default=0)),
                ('week2', models.IntegerField(default=0)),
                ('week3', models.IntegerField(default=0)),
                ('grade_include', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='WorkloadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('grade_num', models.IntegerField(choices=[(1, '高一'), (2, '高二'), (3, '高三')])),
                ('subject', models.CharField(choices=[('语文', '语文'), ('数学', '数学'), ('外语', '外语'), ('政治', '政治'), ('历史', '历史'), ('地理', '地理'), ('物理', '物理'), ('化学', '化学'), ('生物', '生物'), ('美术', '美术'), ('体育与健康', '体育与健康'), ('音乐', '音乐'), ('心理', '心理'), ('信息技术', '信息技术')], max_length=5)),
                ('css', models.CharField(max_length=20)),
                ('cs_n', models.IntegerField()),
                ('week_plans', models.IntegerField()),
                ('week_lessons', models.IntegerField()),
                ('month_plans', models.IntegerField()),
                ('month_lessons', models.IntegerField()),
                ('morning_lessons', models.IntegerField()),
                ('evening_lessons', models.IntegerField()),
                ('headteacher', models.BooleanField(default=False)),
                ('headteacher_n', models.IntegerField(default=0)),
                ('grade_master', models.BooleanField(default=False)),
                ('grade_master_n', models.IntegerField(default=0)),
                ('small_master', models.BooleanField(default=False)),
                ('small_master_n', models.IntegerField(default=0)),
                ('big_master', models.BooleanField(default=False)),
                ('big_master_n', models.IntegerField(default=0)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Task')),
            ],
        ),
    ]
