# Generated by Django 3.0.6 on 2023-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadrecord',
            name='css_format',
            field=models.CharField(default='', max_length=20),
        ),
    ]
