# Generated by Django 3.0.6 on 2023-06-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_workloadrecord_css_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadrecord',
            name='grade',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='month',
            field=models.CharField(choices=[('2023-06', '2023年6月'), ('2023-05', '2023年5月'), ('2023-04', '2023年4月'), ('2023-03', '2023年3月'), ('2023-02', '2023年2月'), ('2023-01', '2023年1月')], max_length=8),
        ),
    ]
