# Generated by Django 3.0.6 on 2023-10-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_auto_20230620_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='grade_include',
            field=models.IntegerField(choices=[(1, '高一'), (2, '高二'), (3, '高三')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='month',
            field=models.CharField(choices=[('2023-10', '2023年10月'), ('2023-09', '2023年9月'), ('2023-08', '2023年8月'), ('2023-07', '2023年7月'), ('2023-06', '2023年6月'), ('2023-05', '2023年5月')], max_length=8),
        ),
    ]
