# Generated by Django 3.0.6 on 2023-10-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0004_auto_20231023_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='week1',
            new_name='weeks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='week2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='week3',
        ),
    ]
