# Generated by Django 3.0.6 on 2023-10-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0005_auto_20231023_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='grade_include',
            new_name='grade',
        ),
    ]
