# Generated by Django 3.0.6 on 2023-10-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0006_auto_20231023_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grade_str',
            field=models.CharField(default='高一', max_length=2),
        ),
    ]
