# Generated by Django 3.0.6 on 2023-10-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0007_task_grade_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='grade_str',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='SubLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_teacher', models.CharField(max_length=5)),
                ('sub_class', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班'), ('高三1班', '高三1班'), ('高三2班', '高三2班'), ('高三3班', '高三3班'), ('高三4班', '高三4班'), ('高三5班', '高三5班'), ('高三6班', '高三6班'), ('高三7班', '高三7班'), ('高三8班', '高三8班'), ('高三9班', '高三9班'), ('高三10班', '高三10班'), ('高三11班', '高三11班'), ('高三12班', '高三12班')], max_length=5)),
                ('sub_time', models.CharField(max_length=50)),
                ('sub_lessons', models.IntegerField(default=0)),
                ('record_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.WorkloadRecord')),
            ],
        ),
    ]
