# Generated by Django 3.0.6 on 2023-11-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0008_auto_20231026_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workloadrecord',
            name='css',
        ),
        migrations.AlterField(
            model_name='task',
            name='month',
            field=models.CharField(choices=[('2023-11', '2023年11月'), ('2023-10', '2023年10月'), ('2023-09', '2023年9月'), ('2023-08', '2023年8月'), ('2023-07', '2023年7月'), ('2023-06', '2023年6月')], max_length=8),
        ),
    ]
