# Generated by Django 3.0.6 on 2023-11-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0009_auto_20231101_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadrecord',
            name='css_format',
            field=models.CharField(default='', max_length=40),
        ),
    ]
