# Generated by Django 3.0.6 on 2023-02-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=11)),
                ('car1', models.CharField(max_length=8)),
                ('is_new_energy1', models.BooleanField()),
                ('car2', models.CharField(default='', max_length=8)),
                ('is_new_energy2', models.BooleanField()),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
