# Generated by Django 3.0.6 on 2023-02-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrecord',
            name='tp',
            field=models.CharField(choices=[('教师', '教师'), ('食堂', '食堂'), ('保安', '保安'), ('物业', '物业')], default='教师', max_length=5),
        ),
    ]
