# Generated by Django 3.0.6 on 2022-11-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('grade', models.CharField(max_length=5)),
                ('total', models.IntegerField(default=0)),
                ('absent_students', models.CharField(max_length=100)),
                ('come', models.IntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('date_str', models.CharField(max_length=10)),
                ('grade_include', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('dorm', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=100)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtoschool.Class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtoschool.Task'),
        ),
    ]
