# Generated by Django 3.0.6 on 2022-11-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='absent_students',
            field=models.CharField(default='', max_length=100),
        ),
    ]
