# Generated by Django 3.0.6 on 2022-11-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0002_auto_20221105_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='absent_students',
            field=models.CharField(default='无', max_length=100),
        ),
    ]
