# Generated by Django 3.0.6 on 2022-11-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0003_auto_20221105_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
    ]
