# Generated by Django 3.0.6 on 2023-09-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletes',
            name='pwd',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
