# Generated by Django 3.0.6 on 2023-09-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_meet', '0002_athletes_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='putname',
            name='athlete_belong',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sport_meet.Athletes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='putname',
            name='item',
            field=models.CharField(choices=[('100米', '100米'), ('200米', '200米'), ('800米', '800米'), ('1500米', '1500米'), ('跳高', '跳高'), ('跳远', '跳远'), ('实心球', '实心球')], max_length=5),
        ),
    ]
