# Generated by Django 3.0.6 on 2023-09-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_meet', '0003_auto_20230914_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletes',
            name='year',
            field=models.CharField(default='2023', max_length=4),
        ),
        migrations.AddField(
            model_name='putname',
            name='year',
            field=models.CharField(default='2023', max_length=4),
        ),
    ]
