# Generated by Django 3.0.6 on 2023-09-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_meet', '0004_auto_20230921_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletes',
            name='year',
        ),
        migrations.RemoveField(
            model_name='putname',
            name='year',
        ),
    ]
