# Generated by Django 3.0.6 on 2024-09-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_meet', '0005_auto_20230921_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletes',
            name='year',
            field=models.CharField(default='2023', max_length=4),
        ),
        migrations.AddField(
            model_name='putname',
            name='year',
            field=models.CharField(default='2023', max_length=4),
        ),
    ]
