"""方便调用的工具类"""
import re


class DataTool:
    """数据类"""

    def __init__(self):
        # 年级为高一、高二
        self.grades = ['高一', '高二']

        # 年级与数字对应
        self.grades_num = {'高一': 1, '高二': 2}

        # 节目表演形式
        self.tp = (
            ('歌曲类', '歌曲类'),
            ('舞蹈类', '舞蹈类'),
            ('语言类', '语言类'),
            ('器乐类', '器乐类'),
            ('其他', '其他（请在节目简介中详细说明）'),
        )

        # 审核顺序
        self.range = {'舞蹈类': 1, '器乐类': 2, '歌曲类': 3, '语言类': 4, '其他': 5}

        # 最多话筒个数
        self.max_macs = 4

        # 项目管理员
        self.managers = ['zz106dyc', '李宪伟', '牛俊雅', '张志云']

        # 匹配数字
        self.num_regex = re.compile(r'\d+')

        # 密钥映射到id
        self.sec = {'038gJF59eo': 122,
                    '07d1wudzRv': 89,
                    '0u9bf1PaMh': 117,
                    '1ECl33tr2x': 12,
                    '1v9QNJtqx8': 141,
                    '2LAYxGCVlS': 10,
                    '2dDaTmxoaK': 166,
                    '2vKEjBh8Gt': 19,
                    '2voLYj39Yb': 77,
                    '35yD7NxazH': 5,
                    '3c1w9YWvZ8': 74,
                    '6JR5pSbuEM': 167,
                    '71LDSm0UgE': 113,
                    '7GpxTMvDPT': 111,
                    '7u6kFZFTha': 21,
                    '90lISfn1Nb': 78,
                    'ANZnL9CPFv': 182,
                    'ASCVqFrwoy': 42,
                    'AvlimYegYB': 169,
                    'B1h21wbYxz': 171,
                    'B4eBISxh2K': 99,
                    'BN6DVAeiJc': 62,
                    'BSMLcr71QT': 147,
                    'BZa2lS7CHX': 142,
                    'Bi0CCpLAIr': 161,
                    'BzNzDS6bbu': 6,
                    'CWialKtCPP': 41,
                    'ClvCtpZFl8': 165,
                    'D7AfoYP1S8': 73,
                    'DNqHCBur0S': 162,
                    'DXToFiBcAU': 158,
                    'DmjpHJCpXG': 79,
                    'Dn0cQWRHIn': 118,
                    'E1UD1MyDQe': 51,
                    'E1cRVODuUY': 88,
                    'E4kD42FkJW': 191,
                    'EL7b4Pd8Ju': 183,
                    'FParDmUfgl': 14,
                    'G4Ky0HqMQS': 43,
                    'G9COHopt42': 72,
                    'GQVQ4zCPmm': 17,
                    'GvLXzPIiwR': 129,
                    'H53Jt4nMg3': 57,
                    'HA44jaIase': 76,
                    'HqljtH2zDU': 174,
                    'IeZO0caMl6': 85,
                    'JRili7jIPz': 188,
                    'Jqi2yngfsB': 157,
                    'JwFdRdUpt8': 97,
                    'KDc3FpGBEc': 94,
                    'KTU2wCW0NQ': 198,
                    'Kc05v10eaS': 64,
                    'KxAgIRbTOr': 3,
                    'Kxrx6AEAxn': 175,
                    'KzPQzWpRmX': 53,
                    'L2Eq9pBL7N': 168,
                    'L4feekaSwa': 52,
                    'L6eMrlReZT': 181,
                    'Lna2djxBoe': 32,
                    'Lrp1KweNYm': 35,
                    'M9wiuhDdcj': 146,
                    'MFbiCsRTEy': 80,
                    'NGOFs0GPM1': 119,
                    'NIEHuf6VTq': 179,
                    'NlAWoYe09V': 59,
                    'O4sgJLrrzH': 109,
                    'P6IRpshPSD': 136,
                    'PeRzUNTp5B': 46,
                    'QM6VC7xeQS': 124,
                    'QUJZYRx4Gy': 128,
                    'QaWkOhGH6W': 178,
                    'QtgbYLPNDh': 123,
                    'R5tnKexA13': 56,
                    'RPbuQwlS99': 47,
                    'Rde3qUApwf': 55,
                    'SiDjGp5TrA': 65,
                    'SjeNLtirxE': 67,
                    'T45QK8j3y5': 151,
                    'TAMqb3tMnt': 180,
                    'TdvLY0zfaj': 25,
                    'TmLjPQpE0l': 194,
                    'Tr4cnMkbqF': 13,
                    'UQAo1SohxH': 133,
                    'UgyWyBJ5Hl': 95,
                    'Uo9brnwLar': 131,
                    'UzyY6JZVDs': 30,
                    'VERidYGkUb': 101,
                    'VXadbAiuDV': 15,
                    'VdHwSZ37cM': 114,
                    'VotinoVJFI': 50,
                    'VxCiSExzAk': 28,
                    'WFX8Clme5p': 103,
                    'WPe111aYgs': 110,
                    'Wk2d4Ne5KX': 195,
                    'X9Q3t4XWpA': 24,
                    'XqM1icrcU5': 66,
                    'XqnkpHUV7A': 120,
                    'Y7CBDlJQPi': 69,
                    'YUlqSUMMBb': 177,
                    'YbwJfOLMWS': 18,
                    'ZV6vJEVDox': 153,
                    'Za2pFqs6cQ': 98,
                    'ZdQksZFAsJ': 38,
                    'a5vXDQXz15': 115,
                    'aPWMJ7oLlv': 173,
                    'aaBsVsnYSe': 189,
                    'bUapitunr7': 172,
                    'bWVvcO775d': 68,
                    'bhdPJkQIe9': 87,
                    'bhr4PxC58B': 176,
                    'bmM4InqUy4': 155,
                    'c7ky5TLCLJ': 163,
                    'c9KRYTvR1b': 1,
                    'cH2xPaF1rI': 100,
                    'cHuweOHJ2h': 84,
                    'ceZRtyAoEG': 63,
                    'cuYw2X9S4T': 140,
                    'd2m36NF9CP': 144,
                    'dUFrSWEUbQ': 61,
                    'dVGDvNqKSJ': 156,
                    'dWko3JpvLK': 149,
                    'dg544gm9S9': 196,
                    'e5KiG2ycg9': 107,
                    'eHCTLjdVtF': 125,
                    'eXaxlUOK1j': 150,
                    'eeHdreeX9c': 106,
                    'fBpUMBU6YQ': 92,
                    'g3ERYj4vz8': 130,
                    'g9syfmsI3C': 170,
                    'gTThMSJULu': 197,
                    'gZjRT3zMRS': 48,
                    'gzSVpigt2M': 34,
                    'hK9G9grhfC': 105,
                    'hUZvim9Tsf': 90,
                    'ht5sX8EJ8M': 45,
                    'iCRnYrs2Fx': 93,
                    'iDLfxrOjKP': 127,
                    'iFpJIcgbpy': 71,
                    'iScXyGpQz7': 200,
                    'iri97MtxYp': 164,
                    'jNVFXJUDcI': 184,
                    'jWzCjtfBas': 121,
                    'jhx7ClR4Go': 27,
                    'k9G8zS8W9s': 192,
                    'kVCOq0E87T': 81,
                    'khYVrCoYD8': 23,
                    'koGWHODKXd': 82,
                    'lTXJ7PkAQ7': 86,
                    'llBMtRIz7w': 126,
                    'm7ZfdOfxO0': 26,
                    'mBEZ6CSCTs': 185,
                    'mCO3ZwTlmS': 11,
                    'mqOs5IOY3b': 135,
                    'n7G1roaJ1K': 49,
                    'nGOxX1g3k4': 112,
                    'nMPnxHJFI6': 102,
                    'ntpVaTcNpe': 75,
                    'nvyaekOcDn': 39,
                    'oJhxxgNXUZ': 104,
                    'oL4p4fuQiZ': 83,
                    'oNwQN2RAYg': 44,
                    'om9PAKcWkc': 22,
                    'oyA9JqOwwG': 134,
                    'p5qCAlqolv': 152,
                    'p7ev00igUK': 160,
                    'pyOn29kE5a': 70,
                    'qiZ2si6yky': 29,
                    'qn1Xr7PMg2': 145,
                    'qwa7hb6t3s': 143,
                    'r2z4lSyerO': 187,
                    'r9ug1V6E9I': 7,
                    'rGHARp6fRY': 20,
                    'rckQGk9nU3': 96,
                    'rtJQO1qJXN': 186,
                    's9yq6nVIrn': 31,
                    'sVORGLe5jn': 137,
                    'sp3c3g7NDL': 139,
                    'ssUZcd5ltG': 37,
                    'sshiHQgxqr': 9,
                    'sxfozms1J9': 138,
                    't5x086P4i5': 33,
                    'tLfyJEtOR5': 4,
                    'tagh4b5Zso': 159,
                    'tp2V3L1Gqn': 91,
                    'tvW4h4HB8I': 190,
                    'twoLY4UPgk': 16,
                    'uHqaSTkRHC': 40,
                    'uKSa90Ykk8': 132,
                    'uNzepw93jc': 60,
                    'uTXYZa4JMA': 58,
                    'ub8b0340V5': 193,
                    'upJrh1aqzR': 36,
                    'uyAaMFoeUg': 2,
                    'vhvv3kG1sP': 154,
                    'w3z3BHAy47': 199,
                    'w8OWOJFPib': 8,
                    'yDfXckMSzy': 116,
                    'ySTxP9PazQ': 54,
                    'zqlVMvgs4z': 108,
                    'zsg0jP6JHm': 148}
        self.secl = ['c9KRYTvR1b',
                     'uyAaMFoeUg',
                     'KxAgIRbTOr',
                     'tLfyJEtOR5',
                     '35yD7NxazH',
                     'BzNzDS6bbu',
                     'r9ug1V6E9I',
                     'w8OWOJFPib',
                     'sshiHQgxqr',
                     '2LAYxGCVlS',
                     'mCO3ZwTlmS',
                     '1ECl33tr2x',
                     'Tr4cnMkbqF',
                     'FParDmUfgl',
                     'VXadbAiuDV',
                     'twoLY4UPgk',
                     'GQVQ4zCPmm',
                     'YbwJfOLMWS',
                     '2vKEjBh8Gt',
                     'rGHARp6fRY',
                     '7u6kFZFTha',
                     'om9PAKcWkc',
                     'khYVrCoYD8',
                     'X9Q3t4XWpA',
                     'TdvLY0zfaj',
                     'm7ZfdOfxO0',
                     'jhx7ClR4Go',
                     'VxCiSExzAk',
                     'qiZ2si6yky',
                     'UzyY6JZVDs',
                     's9yq6nVIrn',
                     'Lna2djxBoe',
                     't5x086P4i5',
                     'gzSVpigt2M',
                     'Lrp1KweNYm',
                     'upJrh1aqzR',
                     'ssUZcd5ltG',
                     'ZdQksZFAsJ',
                     'nvyaekOcDn',
                     'uHqaSTkRHC',
                     'CWialKtCPP',
                     'ASCVqFrwoy',
                     'G4Ky0HqMQS',
                     'oNwQN2RAYg',
                     'ht5sX8EJ8M',
                     'PeRzUNTp5B',
                     'RPbuQwlS99',
                     'gZjRT3zMRS',
                     'n7G1roaJ1K',
                     'VotinoVJFI',
                     'E1UD1MyDQe',
                     'L4feekaSwa',
                     'KzPQzWpRmX',
                     'ySTxP9PazQ',
                     'Rde3qUApwf',
                     'R5tnKexA13',
                     'H53Jt4nMg3',
                     'uTXYZa4JMA',
                     'NlAWoYe09V',
                     'uNzepw93jc',
                     'dUFrSWEUbQ',
                     'BN6DVAeiJc',
                     'ceZRtyAoEG',
                     'Kc05v10eaS',
                     'SiDjGp5TrA',
                     'XqM1icrcU5',
                     'SjeNLtirxE',
                     'bWVvcO775d',
                     'Y7CBDlJQPi',
                     'pyOn29kE5a',
                     'iFpJIcgbpy',
                     'G9COHopt42',
                     'D7AfoYP1S8',
                     '3c1w9YWvZ8',
                     'ntpVaTcNpe',
                     'HA44jaIase',
                     '2voLYj39Yb',
                     '90lISfn1Nb',
                     'DmjpHJCpXG',
                     'MFbiCsRTEy',
                     'kVCOq0E87T',
                     'koGWHODKXd',
                     'oL4p4fuQiZ',
                     'cHuweOHJ2h',
                     'IeZO0caMl6',
                     'lTXJ7PkAQ7',
                     'bhdPJkQIe9',
                     'E1cRVODuUY',
                     '07d1wudzRv',
                     'hUZvim9Tsf',
                     'tp2V3L1Gqn',
                     'fBpUMBU6YQ',
                     'iCRnYrs2Fx',
                     'KDc3FpGBEc',
                     'UgyWyBJ5Hl',
                     'rckQGk9nU3',
                     'JwFdRdUpt8',
                     'Za2pFqs6cQ',
                     'B4eBISxh2K',
                     'cH2xPaF1rI',
                     'VERidYGkUb',
                     'nMPnxHJFI6',
                     'WFX8Clme5p',
                     'oJhxxgNXUZ',
                     'hK9G9grhfC',
                     'eeHdreeX9c',
                     'e5KiG2ycg9',
                     'zqlVMvgs4z',
                     'O4sgJLrrzH',
                     'WPe111aYgs',
                     '7GpxTMvDPT',
                     'nGOxX1g3k4',
                     '71LDSm0UgE',
                     'VdHwSZ37cM',
                     'a5vXDQXz15',
                     'yDfXckMSzy',
                     '0u9bf1PaMh',
                     'Dn0cQWRHIn',
                     'NGOFs0GPM1',
                     'XqnkpHUV7A',
                     'jWzCjtfBas',
                     '038gJF59eo',
                     'QtgbYLPNDh',
                     'QM6VC7xeQS',
                     'eHCTLjdVtF',
                     'llBMtRIz7w',
                     'iDLfxrOjKP',
                     'QUJZYRx4Gy',
                     'GvLXzPIiwR',
                     'g3ERYj4vz8',
                     'Uo9brnwLar',
                     'uKSa90Ykk8',
                     'UQAo1SohxH',
                     'oyA9JqOwwG',
                     'mqOs5IOY3b',
                     'P6IRpshPSD',
                     'sVORGLe5jn',
                     'sxfozms1J9',
                     'sp3c3g7NDL',
                     'cuYw2X9S4T',
                     '1v9QNJtqx8',
                     'BZa2lS7CHX',
                     'qwa7hb6t3s',
                     'd2m36NF9CP',
                     'qn1Xr7PMg2',
                     'M9wiuhDdcj',
                     'BSMLcr71QT',
                     'zsg0jP6JHm',
                     'dWko3JpvLK',
                     'eXaxlUOK1j',
                     'T45QK8j3y5',
                     'p5qCAlqolv',
                     'ZV6vJEVDox',
                     'vhvv3kG1sP',
                     'bmM4InqUy4',
                     'dVGDvNqKSJ',
                     'Jqi2yngfsB',
                     'DXToFiBcAU',
                     'tagh4b5Zso',
                     'p7ev00igUK',
                     'Bi0CCpLAIr',
                     'DNqHCBur0S',
                     'c7ky5TLCLJ',
                     'iri97MtxYp',
                     'ClvCtpZFl8',
                     '2dDaTmxoaK',
                     '6JR5pSbuEM',
                     'L2Eq9pBL7N',
                     'AvlimYegYB',
                     'g9syfmsI3C',
                     'B1h21wbYxz',
                     'bUapitunr7',
                     'aPWMJ7oLlv',
                     'HqljtH2zDU',
                     'Kxrx6AEAxn',
                     'bhr4PxC58B',
                     'YUlqSUMMBb',
                     'QaWkOhGH6W',
                     'NIEHuf6VTq',
                     'TAMqb3tMnt',
                     'L6eMrlReZT',
                     'ANZnL9CPFv',
                     'EL7b4Pd8Ju',
                     'jNVFXJUDcI',
                     'mBEZ6CSCTs',
                     'rtJQO1qJXN',
                     'r2z4lSyerO',
                     'JRili7jIPz',
                     'aaBsVsnYSe',
                     'tvW4h4HB8I',
                     'E4kD42FkJW',
                     'k9G8zS8W9s',
                     'ub8b0340V5',
                     'TmLjPQpE0l',
                     'Wk2d4Ne5KX',
                     'dg544gm9S9',
                     'gTThMSJULu',
                     'KTU2wCW0NQ',
                     'w3z3BHAy47',
                     'iScXyGpQz7']

    def get_all_classes(self):
        """以二维元组形式返回所有班级字符串供模型的choices属性使用"""
        # 初始化列表
        css = []

        for grade in self.grades:
            for i in range(1, 13):
                # 生成班级字符串
                gc = grade + str(i) + '班'

                # 加入二元组
                css.append((gc, gc))

        # 返回元组
        return tuple(css)

    def get_mac_nums(self):
        """返回话筒个数范围选项"""
        # 初始化列表
        nums = []

        for num in range(self.max_macs + 1):
            nums.append((num, str(num)))

        return tuple(nums)

    def get_all_include_teacher(self):
        """增加教师选项"""
        css = list(self.get_all_classes())
        css.append(('教师', '教师'))
        return tuple(css)

    def get_cs_tup(self, gc):
        """根据年级班级字符串返回年级班级数字二元组"""
        grade = self.grades_num[gc[:2]]
        cs = int(self.num_regex.findall(gc)[0])
        return grade, cs
