# Generated by Django 3.0.6 on 2025-06-26 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_num', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=2)),
                ('cs', models.IntegerField(choices=[(1, '1班'), (2, '2班'), (3, '3班'), (4, '4班'), (5, '5班'), (6, '6班'), (7, '7班'), (8, '8班'), (9, '9班'), (10, '10班'), (11, '11班'), (12, '12班')])),
                ('class_and_grade', models.CharField(max_length=5)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateField(default=datetime.datetime(2025, 6, 26, 9, 8, 0, 5614))),
                ('to_come', models.IntegerField()),
                ('short_abst', models.IntegerField(default=0)),
                ('work_abst', models.IntegerField(default=0)),
                ('quality_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('act_come', models.IntegerField()),
                ('late_come', models.IntegerField(default=0)),
                ('no_wear', models.IntegerField(default=0)),
                ('escape', models.IntegerField(default=0)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('owner', models.CharField(default='', max_length=8)),
                ('owner_show', models.CharField(default='', max_length=13)),
                ('pwd', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ShortAbst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_num', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=2)),
                ('cs', models.IntegerField(choices=[(1, '1班'), (2, '2班'), (3, '3班'), (4, '4班'), (5, '5班'), (6, '6班'), (7, '7班'), (8, '8班'), (9, '9班'), (10, '10班'), (11, '11班'), (12, '12班')])),
                ('class_and_grade', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=5)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateField(default=datetime.datetime(2025, 6, 26, 9, 8, 0, 5614))),
                ('owner', models.CharField(blank=True, default='', max_length=8)),
                ('owner_show', models.CharField(default='', max_length=13)),
                ('pwd', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
