# Generated by Django 3.0.6 on 2025-06-26 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_eva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisescore',
            name='class_and_grade',
            field=models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班')], max_length=5),
        ),
        migrations.AlterField(
            model_name='exercisescore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 6, 26, 9, 19, 54, 305010)),
        ),
        migrations.AlterField(
            model_name='exercisescore',
            name='grade',
            field=models.CharField(choices=[('高一', '高一'), ('高二', '高二')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shortabst',
            name='class_and_grade',
            field=models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班')], max_length=5),
        ),
        migrations.AlterField(
            model_name='shortabst',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 6, 26, 9, 19, 54, 305010)),
        ),
        migrations.AlterField(
            model_name='shortabst',
            name='grade',
            field=models.CharField(choices=[('高一', '高一'), ('高二', '高二')], max_length=2),
        ),
    ]
