# Generated by Django 3.0.6 on 2025-06-30 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_eva', '0002_auto_20250626_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisescore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 6, 30, 9, 49, 34, 634903)),
        ),
        migrations.AlterField(
            model_name='shortabst',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 6, 30, 9, 49, 34, 635905)),
        ),
    ]
