# Generated by Django 3.0.6 on 2025-11-05 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_eva', '0003_auto_20250630_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECOScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_num', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('高一', '高一'), ('高二', '高二')], max_length=2)),
                ('cs', models.IntegerField(choices=[(1, '1班'), (2, '2班'), (3, '3班'), (4, '4班'), (5, '5班'), (6, '6班'), (7, '7班'), (8, '8班'), (9, '9班'), (10, '10班'), (11, '11班'), (12, '12班')])),
                ('class_and_grade', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班')], max_length=5)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateField(default=datetime.datetime(2025, 11, 5, 16, 20, 54, 49652))),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(blank=True, default='', max_length=8)),
                ('owner_show', models.CharField(default='', max_length=13)),
                ('pwd', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='exercisescore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 11, 5, 16, 20, 54, 48366)),
        ),
        migrations.AlterField(
            model_name='shortabst',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 11, 5, 16, 20, 54, 48948)),
        ),
    ]
