# Generated by Django 3.0.6 on 2023-06-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BKRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('id_number', models.CharField(max_length=18)),
                ('bank_id', models.CharField(max_length=19)),
                ('bank_tp', models.CharField(max_length=10)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
