# Generated by Django 3.0.6 on 2023-06-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkrecord',
            name='work_point',
            field=models.CharField(choices=[('106初中', '106初中'), ('106高中', '106高中'), ('54中', '54中'), ('84中', '84中')], default='106初中', max_length=5),
        ),
    ]
