# Generated by Django 3.0.6 on 2022-11-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcleanrecord',
            name='grade_num',
            field=models.IntegerField(default=0),
        ),
    ]
