# Generated by Django 3.0.6 on 2023-02-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0003_classcleanrecord_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcleanrecord',
            name='tm',
            field=models.CharField(choices=[('早上', '早上'), ('中午', '中午')], default='早上', max_length=2),
        ),
    ]
