# Generated by Django 3.0.6 on 2023-02-20 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0004_classcleanrecord_tm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 2, 20, 8, 57, 11, 779443)),
        ),
    ]
