# Generated by Django 3.0.6 on 2023-03-28 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0005_auto_20230220_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcleanrecord',
            name='area',
            field=models.CharField(default='未设置', max_length=20),
        ),
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 8, 34, 4, 302345)),
        ),
    ]
