# Generated by Django 3.0.6 on 2023-04-03 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0006_auto_20230328_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcleanrecord',
            name='area',
            field=models.CharField(choices=[('教室', '教室'), ('画室', '画室'), ('走廊', '走廊'), ('1～2西楼梯', '1～2西楼梯'), ('1～2东楼梯', '1～2东楼梯'), ('2～3西楼梯', '2～3西楼梯'), ('2～3东楼梯', '2～3东楼梯'), ('3～4西楼梯', '3～4西楼梯'), ('3～4东楼梯', '3～4东楼梯'), ('4～5西楼梯', '4～5西楼梯'), ('4～5东楼梯', '4～5东楼梯'), ('二层西窗', '二层西窗'), ('二层东窗', '二层东窗'), ('三层西窗', '三层西窗'), ('三层东窗', '三层东窗'), ('四层西窗', '四层西窗'), ('四层东窗', '四层东窗'), ('二层南北空地', '二层南北空地'), ('三层南北空地', '三层南北空地')], default='未设置', max_length=20),
        ),
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 8, 8, 20, 43265)),
        ),
    ]
