# Generated by Django 3.0.6 on 2024-09-26 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0007_auto_20230403_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCleanScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=2)),
                ('grade_num', models.IntegerField(default=0)),
                ('cs', models.IntegerField(choices=[(1, '1班'), (2, '2班'), (3, '3班'), (4, '4班'), (5, '5班'), (6, '6班'), (7, '7班'), (8, '8班'), (9, '9班'), (10, '10班'), (11, '11班'), (12, '12班')])),
                ('class_and_grade', models.CharField(max_length=5)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateField(default=datetime.datetime(2024, 9, 26, 12, 6, 43, 665851))),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 12, 6, 43, 665851)),
        ),
    ]
