# Generated by Django 3.0.6 on 2024-09-26 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0008_auto_20240926_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcleanscore',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 12, 15, 1, 91800)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 12, 15, 1, 91800)),
        ),
    ]
