# Generated by Django 3.0.6 on 2024-09-26 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0009_auto_20240926_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcleanscore',
            name='owner',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 12, 29, 48, 761030)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 12, 29, 48, 762030)),
        ),
    ]
