# Generated by Django 3.0.6 on 2024-09-26 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0010_auto_20240926_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 16, 44, 28, 182482)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 16, 44, 28, 183483)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='owner',
            field=models.CharField(max_length=8),
        ),
    ]
