# Generated by Django 3.0.6 on 2024-09-28 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0011_auto_20240926_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcleanscore',
            name='pwd',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 28, 18, 22, 15, 225212)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 28, 18, 22, 15, 226217)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='owner',
            field=models.CharField(max_length=5),
        ),
    ]
