# Generated by Django 3.0.6 on 2024-09-28 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0012_auto_20240928_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 28, 19, 18, 20, 420891)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 28, 19, 18, 20, 420891)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='owner',
            field=models.CharField(choices=[('秦萌', '秦萌'), ('李安琪', '李安琪'), ('李嘉仪', '李嘉仪'), ('刘笑含', '刘笑含'), ('景思源', '景思源'), ('曾子羊', '曾子羊'), ('章家绮', '章家绮'), ('钟筱涵', '钟筱涵'), ('王晨曦', '王晨曦'), ('谷昭希', '谷昭希'), ('田雨泽', '田雨泽'), ('张兴隆', '张兴隆'), ('侯柯欣', '侯柯欣'), ('陈艺元', '陈艺元'), ('种孜硕', '种孜硕'), ('赵妙格', '赵妙格'), ('郭欣怡', '郭欣怡'), ('徐婉婷', '徐婉婷'), ('王粲然', '王粲然'), ('赵婉妤', '赵婉妤'), ('杜佩颖', '杜佩颖'), ('丁心茗', '丁心茗'), ('贺诣然', '贺诣然'), ('常艺馨', '常艺馨'), ('王诗瑶', '王诗瑶'), ('赵乃琳', '赵乃琳'), ('侯宇凡', '侯宇凡')], max_length=5),
        ),
    ]
