# Generated by Django 3.0.6 on 2024-09-28 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0013_auto_20240928_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 28, 19, 19, 23, 122308)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 28, 19, 19, 23, 122308)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='pwd',
            field=models.CharField(max_length=6),
        ),
    ]
