# Generated by Django 3.0.6 on 2025-01-21 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0014_auto_20240928_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 14, 25, 6, 812797)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 14, 25, 6, 812797)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='owner',
            field=models.CharField(default='', max_length=8),
        ),
    ]
