# Generated by Django 3.0.6 on 2025-01-21 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0015_auto_20250121_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcleanscore',
            name='owner_show',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 15, 21, 26, 645144)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 15, 21, 26, 645144)),
        ),
    ]
