# Generated by Django 3.0.6 on 2025-04-02 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0016_auto_20250121_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutLookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=2)),
                ('grade_num', models.IntegerField(default=0)),
                ('cs', models.IntegerField(choices=[(1, '1班'), (2, '2班'), (3, '3班'), (4, '4班'), (5, '5班'), (6, '6班'), (7, '7班'), (8, '8班'), (9, '9班'), (10, '10班'), (11, '11班'), (12, '12班')])),
                ('class_and_grade', models.CharField(max_length=5)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateField(default=datetime.datetime(2025, 4, 2, 21, 30, 29, 541534))),
                ('hair_record', models.CharField(max_length=200)),
                ('hair_n', models.IntegerField()),
                ('jewelry_record', models.CharField(max_length=200)),
                ('jewelry_n', models.IntegerField()),
                ('owner', models.CharField(default='', max_length=8)),
                ('owner_show', models.CharField(default='', max_length=13)),
                ('pwd', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 21, 30, 29, 541534)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 21, 30, 29, 541534)),
        ),
    ]
