# Generated by Django 3.0.6 on 2025-04-02 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classclean', '0017_auto_20250402_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcleanrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 23, 15, 26, 236890)),
        ),
        migrations.AlterField(
            model_name='classcleanscore',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 23, 15, 26, 236890)),
        ),
        migrations.AlterField(
            model_name='outlookrecord',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 23, 15, 26, 238132)),
        ),
        migrations.AlterField(
            model_name='outlookrecord',
            name='hair_record',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='outlookrecord',
            name='jewelry_record',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
