# Generated by Django 3.0.6 on 2023-03-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tm', models.DateTimeField()),
                ('place', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('department', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三'), ('美术', '美术'), ('体音', '体音'), ('行管', '行管')], max_length=2)),
                ('phone_number', models.CharField(max_length=11)),
                ('activity_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='put_name.Activities')),
            ],
        ),
    ]
