# Generated by Django 3.0.6 on 2023-03-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
