# Generated by Django 3.0.6 on 2023-03-14 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put_name', '0002_activities_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 10, 26, 30, 665065)),
        ),
        migrations.AddField(
            model_name='participant',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 10, 26, 30, 665485)),
        ),
    ]
