# Generated by Django 3.0.6 on 2023-03-14 02:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('put_name', '0003_auto_20230314_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activities',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 10, 32, 8, 557741)),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 10, 32, 8, 558199)),
        ),
    ]
