# Generated by Django 3.0.6 on 2023-03-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put_name', '0004_auto_20230314_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
