# Generated by Django 3.0.6 on 2023-03-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put_name', '0005_auto_20230314_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='tm_str',
            field=models.CharField(default='2023-01-01T00:00', max_length=16),
        ),
    ]
