# Generated by Django 3.0.6 on 2023-03-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put_name', '0006_activities_tm_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='tm_str',
            field=models.CharField(default='2023-03-14T11:22', max_length=16),
        ),
    ]
