# Generated by Django 3.0.6 on 2023-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put_name', '0007_auto_20230314_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='out_of_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='tm_str',
            field=models.CharField(default='2023-03-14T16:54', max_length=16),
        ),
    ]
