# Generated by Django 3.0.6 on 2023-06-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put_name', '0008_auto_20230314_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='tm_str',
            field=models.CharField(default='2023-06-21T08:52', max_length=16),
        ),
    ]
