# Generated by Django 3.0.6 on 2023-02-14 05:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=2)),
                ('grade_num', models.IntegerField(default=0)),
                ('cs', models.IntegerField(choices=[(1, '1班'), (2, '2班'), (3, '3班'), (4, '4班'), (5, '5班'), (6, '6班'), (7, '7班'), (8, '8班'), (9, '9班'), (10, '10班'), (11, '11班'), (12, '12班')])),
                ('class_and_grade', models.CharField(max_length=5)),
                ('late_students', models.CharField(max_length=200)),
                ('late_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 2, 14, 13, 53, 53, 903775))),
                ('date_str', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LateStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tm', models.CharField(choices=[('早上', '早上'), ('中午', '中午')], max_length=2)),
                ('class_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='late.ClassRecord')),
            ],
        ),
        migrations.AddField(
            model_name='classrecord',
            name='date_happened',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='late.DateRecord'),
        ),
    ]
