# Generated by Django 3.0.6 on 2023-02-15 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('late', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrecord',
            name='late_students',
        ),
        migrations.AddField(
            model_name='classrecord',
            name='late_students_am',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='late_students_pm',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='daterecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 15, 15, 56, 35, 456896)),
        ),
    ]
