# Generated by Django 3.0.6 on 2023-02-15 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('late', '0002_auto_20230215_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='late_students_am',
            field=models.CharField(default='无', max_length=200),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='late_students_pm',
            field=models.CharField(default='无', max_length=200),
        ),
        migrations.AlterField(
            model_name='daterecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 15, 16, 29, 35, 875392)),
        ),
    ]
