# Generated by Django 3.0.6 on 2023-02-15 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('late', '0003_auto_20230215_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='has_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='daterecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 15, 17, 35, 8, 701416)),
        ),
    ]
