# Generated by Django 3.0.6 on 2023-06-21 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('late', '0004_auto_20230215_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 8, 52, 5, 302153)),
        ),
    ]
