# Generated by Django 3.0.6 on 2023-04-12 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mt', models.CharField(max_length=5)),
                ('mt_class', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班'), ('教师', '教师')], max_length=5)),
                ('owner', models.CharField(max_length=5)),
                ('owner_class', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班')], max_length=5)),
                ('owner_phone', models.CharField(max_length=11)),
                ('desc', models.TextField()),
                ('drawing', models.ImageField(upload_to='costume/')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tp', models.CharField(choices=[('歌曲', '歌曲'), ('舞蹈', '舞蹈'), ('话剧', '话剧'), ('小品', '小品'), ('曲艺', '曲艺'), ('其他', '其他（请在节目简介中相信说明）')], max_length=2)),
                ('owner', models.CharField(max_length=5)),
                ('owner_class', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班')], max_length=5)),
                ('owner_phone', models.CharField(max_length=11)),
                ('mac_nums', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('class_belong', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班'), ('教师', '教师')], max_length=5)),
                ('program_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artday.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('class_belong', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班')], max_length=5)),
                ('costume_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artday.Costume')),
            ],
        ),
    ]
