# Generated by Django 3.0.6 on 2023-04-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costume',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='costume/'),
        ),
    ]
