# Generated by Django 3.0.6 on 2023-04-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artday', '0002_auto_20230412_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='etc',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='tp',
            field=models.CharField(choices=[('歌曲', '歌曲'), ('舞蹈', '舞蹈'), ('话剧', '话剧'), ('小品', '小品'), ('曲艺', '曲艺'), ('其他', '其他（请在节目简介中详细说明）')], max_length=2),
        ),
    ]
