# Generated by Django 3.0.6 on 2023-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artday', '0003_auto_20230412_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='etc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
