# Generated by Django 3.0.6 on 2023-04-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artday', '0004_auto_20230413_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='tp',
            field=models.CharField(choices=[('歌曲类', '歌曲类'), ('舞蹈类', '舞蹈类'), ('语言类', '语言类'), ('器乐类', '器乐类'), ('其他', '其他（请在节目简介中详细说明）')], max_length=3),
        ),
    ]
