# Generated by Django 3.0.6 on 2023-05-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artday', '0005_auto_20230418_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
