# Generated by Django 3.0.6 on 2024-04-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artday', '0006_costume_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume',
            name='year',
            field=models.CharField(default='2023', max_length=4),
        ),
        migrations.AddField(
            model_name='program',
            name='year',
            field=models.CharField(default='2023', max_length=4),
        ),
    ]
