# Generated by Django 3.0.6 on 2024-04-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artday', '0007_auto_20240413_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume',
            name='sec',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='program',
            name='sec',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
