# Generated by Django 3.0.6 on 2023-04-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='club_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club_info.Club'),
            preserve_default=False,
        ),
    ]
