# Generated by Django 3.0.6 on 2023-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_info', '0002_member_club_belong'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='nums',
            field=models.IntegerField(default=0),
        ),
    ]
