# Generated by Django 3.0.6 on 2025-01-09 05:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('desc', models.TextField(blank=True)),
                ('code', models.CharField(max_length=2)),
                ('work_abst1', models.BooleanField(default=False)),
                ('work_abst2', models.BooleanField(default=False)),
                ('head_name', models.CharField(choices=[('部长', '(副)部长'), ('主席', '(副)主席')], max_length=2)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2025, 1, 9))),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=11)),
                ('current', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=5)),
                ('class_and_grade', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班')], max_length=5)),
                ('level', models.IntegerField(choices=[(0, '干事'), (1, '副职'), (2, '正职')], default=0)),
                ('main_work', models.CharField(blank=True, max_length=100)),
                ('work_abst1', models.BooleanField(default=False)),
                ('work_abst2', models.BooleanField(default=False)),
                ('call', models.CharField(max_length=9)),
                ('code', models.CharField(max_length=8)),
                ('pwd', models.CharField(default='000000', max_length=6)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='su_manage.Department')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='su_manage.SchoolYear')),
            ],
        ),
    ]
