# Generated by Django 3.0.6 on 2025-01-10 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 1, 10)),
        ),
    ]
