# Generated by Django 3.0.6 on 2025-01-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_manage', '0002_auto_20250110_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code_int',
            field=models.IntegerField(default=0),
        ),
    ]
