# Generated by Django 3.0.6 on 2025-01-15 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_manage', '0003_department_code_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='master',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 1, 15)),
        ),
    ]
