# Generated by Django 3.0.6 on 2025-01-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_manage', '0005_auto_20250117_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='usercall',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='department',
            name='master',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
