# Generated by Django 3.0.6 on 2025-01-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('su_manage', '0006_auto_20250117_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='usercall',
        ),
    ]
