# Generated by Django 3.0.6 on 2025-01-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_manage', '0007_remove_studentuser_usercall'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='master_str',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
