# Generated by Django 3.0.6 on 2025-02-28 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_manage', '0008_department_master_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='work_abst1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='work_abst1',
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 2, 28)),
        ),
    ]
