# Generated by Django 3.0.6 on 2023-03-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongLeaveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('class_and_grade', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班')], max_length=5)),
                ('grade', models.CharField(max_length=2)),
                ('cs', models.IntegerField()),
                ('end_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
