# Generated by Django 3.0.6 on 2023-03-30 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('long_leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=2)),
                ('cs', models.CharField(choices=[('1班', '1班'), ('2班', '2班'), ('3班', '3班'), ('4班', '4班'), ('5班', '5班'), ('6班', '6班'), ('7班', '7班'), ('8班', '8班'), ('9班', '9班'), ('10班', '10班'), ('11班', '11班'), ('12班', '12班')], max_length=3)),
                ('grade_num', models.IntegerField()),
                ('cs_num', models.IntegerField()),
                ('class_and_grade', models.CharField(max_length=5)),
                ('total', models.IntegerField()),
                ('leave', models.IntegerField()),
                ('come', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AbsentStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('reason', models.CharField(max_length=20)),
                ('class_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='long_leave.ClassInfo')),
            ],
        ),
    ]
