# Generated by Django 3.0.6 on 2023-03-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_leave', '0002_absentstudents_classinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='leave',
        ),
    ]
