# Generated by Django 3.0.6 on 2024-09-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_leave', '0003_remove_classinfo_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='longleaverecord',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='cs',
            field=models.CharField(choices=[('1班', '1班'), ('2班', '2班'), ('3班', '3班'), ('4班', '4班'), ('5班', '5班'), ('6班', '6班'), ('7班', '7班'), ('8班', '8班'), ('9班', '9班'), ('10班', '10班'), ('11班', '11班'), ('12班', '12班'), ('13班', '13班')], max_length=3),
        ),
    ]
