# Generated by Django 3.0.6 on 2025-01-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_leave', '0004_auto_20240926_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='longleaverecord',
            name='tp',
            field=models.CharField(choices=[('早操和课间操', '早操和课间操'), ('仅早操', '仅早操'), ('仅课间操', '仅课间操')], default='早操和课间操', max_length=6),
        ),
    ]
