# Generated by Django 3.0.6 on 2025-02-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_leave', '0005_longleaverecord_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longleaverecord',
            name='tp',
            field=models.BooleanField(default=False),
        ),
    ]
