# Generated by Django 3.0.6 on 2025-11-20 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_leave', '0006_auto_20250228_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2025, 11, 20))),
                ('date_str', models.CharField(max_length=10)),
                ('grade_include', models.CharField(max_length=10)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
