# Generated by Django 3.0.6 on 2025-11-24 08:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0029_auto_20251124_1648'),
        ('long_leave', '0007_staytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staytask',
            name='date',
            field=models.DateField(default=datetime.date(2025, 11, 24)),
        ),
        migrations.CreateModel(
            name='StayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('class_and_grade', models.CharField(choices=[('高一1班', '高一1班'), ('高一2班', '高一2班'), ('高一3班', '高一3班'), ('高一4班', '高一4班'), ('高一5班', '高一5班'), ('高一6班', '高一6班'), ('高一7班', '高一7班'), ('高一8班', '高一8班'), ('高一9班', '高一9班'), ('高一10班', '高一10班'), ('高一11班', '高一11班'), ('高一12班', '高一12班'), ('高二1班', '高二1班'), ('高二2班', '高二2班'), ('高二3班', '高二3班'), ('高二4班', '高二4班'), ('高二5班', '高二5班'), ('高二6班', '高二6班'), ('高二7班', '高二7班'), ('高二8班', '高二8班'), ('高二9班', '高二9班'), ('高二10班', '高二10班'), ('高二11班', '高二11班'), ('高二12班', '高二12班'), ('高三1班', '高三1班'), ('高三2班', '高三2班'), ('高三3班', '高三3班'), ('高三4班', '高三4班'), ('高三5班', '高三5班'), ('高三6班', '高三6班'), ('高三7班', '高三7班'), ('高三8班', '高三8班'), ('高三9班', '高三9班'), ('高三10班', '高三10班'), ('高三11班', '高三11班'), ('高三12班', '高三12班')], max_length=5)),
                ('grade', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=2)),
                ('grade_num', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('dorm', models.CharField(max_length=8)),
                ('bed', models.IntegerField()),
                ('student_related', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scores.NewStudent')),
                ('task_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='long_leave.StayTask')),
            ],
        ),
    ]
